### ISSUE TITLE
Update guppy-commit-msg package for new guppy-cli version

### ISSUE THREAD

**Issue by vasily-shakhov** [therealklanni/guppy-commit-msg#1]
There is package https://www.npmjs.com/package/guppy-pre-commit for pre-commit hook. It wonderful and works nicely. It has version 0.2.1.

There is package https://www.npmjs.com/package/guppy-commit-msg for commit-message hook. 
It has version 0.1.0 and don't work right after installing.

If i go to .git/hooks and replace content if commit.msg file with content from pre-commit file all works correctly.

Can u please update https://www.npmjs.com/package/guppy-commit-msg package so it will work in the same way as guppy-pre-commit?

The difference is version of guppy-cli required (0.2.4 vs 0.3.0)

**Comment by therealklanni** [comment]
Thanks, I will update this soon.

**Comment by therealklanni** [comment]
Published v0.2.0
