### ISSUE TITLE
Update guppy-commit-msg npm package

### ISSUE THREAD

**Issue by Lukinoh** [therealklanni/guppy-commit-msg#5]
Hi,

The version available on NPM (0.2.0)  does not reflect the modification of the version of gulp-cli dependency. It is stuck to ^0.3.1. Hence, the hook does not work. Is it possible to publish the up-to-date version, please.

Thanks for your great works!

**Comment by therealklanni** [comment]
Sorry for the delay, I've been buried in issues and PRs, been slowly getting to them all. 

Just checked, and it looks like this package is on guppy-cli@1.0.1, so you should be good!
